services:
  teamspeak:
    image: teamspeak
    restart: always
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: ${USER}
      TS3SERVER_DB_PASSWORD: ${PASSWORD}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    networks:
      - tsnet
      - web
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {$PASSWORD}
      MYSQL_DATABASE: teamspeak
    networks:
    - tsnet

networks:
  tsnet:
    driver: bridge
  web:
    external: true
    name: web
